#!/usr/bin/env bash

function exit_with_error() {
    error_message=$1
    tput setaf 1
    echo $1
    tput sgr0
    exit 1
}

function ensure_env() {
    if [ -z "${!1}" ]; then
        exit_with_error "Missing environment variable \"$1\""
    fi
}

function print_usage() {
    echo "Usage: $DEVENV_NAME apply [--help] [--dry-run]"
    echo ""
    title "Summary"
    echo "This command will apply your devenv configuration to your home directory."
    echo ""
    title "Options"
    echo "--dry-run: Prints everything that would be done by running this command without actually doing anything."
    echo "--help: Shows this page"
}

function print_dry_run_message() {
    message="This is a dry run, nothing will be touched"
    length=${#message}

    horizontal_bar=$(yes "═" | head "-$length" | tr -d "\n")

    tput setaf 1
    echo "╔═${horizontal_bar}═╗"
    echo "║ $message ║"
    echo "╚═${horizontal_bar}═╝"
    tput sgr0
}

function has_option() {
    option_name=$1
    if [ -z $option_name ]; then
        exit_with_error "No option name provided"
    fi

    args=${@:2}
    for arg in $args; do
        if [ "$arg" == "$option_name" ]; then
            echo '1'
            return 0
        fi
    done

    echo '0'
}

function copy_configs() {
    config_path="$DEVENV_CONFIG_DIR/home"

    if [ ! -d "$config_path" ]; then
        echo "The directory $(path "\"$config_path\"") does not exist, nothing to apply."
        return 0
    fi
    group_start 0 "Applying files from $(path "\"$config_path\"")"

    pushd "$config_path" &> /dev/null
    for entry in * .[^.]*; do
        if [ -f $entry ]; then
            group 1 "Applying $(path "~/$entry")" -n

            if [ "$dry_run" == "0" ]; then
                copy_result=$(cp "$config_path/$entry" "$HOME/$entry" 2>&1)
                if [ $? -eq 0 ]; then
                    tput setaf 2
                    echo " 🗸"
                    tput sgr0
                else
                    tput setaf 1
                    echo " 🞪"
                    tput sgr0
                    group_end 0
                    exit_with_error "Error occured while copying: $copy_result"
                fi
            else
                tput setaf 2
                echo " 🗸"
                tput sgr0
            fi
        fi
    done
    popd &> /dev/null

    group_end 0
}

ensure_env "DEVENV_CONFIG_DIR"
ensure_env "DEVENV_DIR"
ensure_env "DEVENV_NAME"

help=$(has_option "--help" $@)
dry_run=$(has_option "--dry-run" $@)

source "$DEVENV_DIR/formatting"

if [ "$help" == "1" ]; then
    print_usage
    exit 0
fi

if [ ! -d "$DEVENV_CONFIG_DIR" ]; then
    echo "The directory $(path "\"$DEVENV_CONFIG_DIR\"") does not exist, nothing to apply."
    exit 0
fi


if [ "$dry_run" == "1" ]; then
    print_dry_run_message
fi

copy_configs
