#!/usr/bin/env bash

function title() {
    tput bold
    echo $1
    tput sgr0
}

function path() {
    tput setaf 3 sitm
    echo -n $1
    tput sgr0
}

function _group_prefix() {
    depth=${1:-0}
    while [ $depth -gt 0 ]; do
        echo -n "│"
        depth=$(( $depth - 1 ))
    done
}

function group_start() {
    _group_prefix $1
    echo "┌── $2 ─"
}

function group() {
    _group_prefix $1
    echo " $2"
}


function group_end() {
    _group_prefix $1
    echo "└─"
}
