#!/usr/bin/env bash

function title() {
    tput bold
    echo $1
    tput sgr0
}

function path() {
    tput setaf 3 sitm
    echo -n $1
    tput sgr0
}

function _group_prefix() {
    local depth=${1:-0}
    while [ $depth -gt 0 ]; do
        echo -n "│"
        depth=$(( $depth - 1 ))
    done
}

function group_start() {
    _group_prefix $1
    echo "┌── $2 ─"
}

function group() {
    _group_prefix $1
    echo $3 " $2"
}


function group_end() {
    _group_prefix $1
    echo "└─"
}

function print_dry_run_message() {
    local message="This is a dry run, nothing will be touched"
    local length=${#message}

    local horizontal_bar=$(yes "═" | head "-$length" | tr -d "\n")

    tput setaf 1
    echo "╔═${horizontal_bar}═╗"
    echo "║ $message ║"
    echo "╚═${horizontal_bar}═╝"
    tput sgr0
}

